FROM debian:buster
MAINTAINER AR4 GmbH <office@ar4.io>

ENV TERM=xterm
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
apt-utils \
unzip \
make \
p7zip-full \
libusb-1.0-0-dev \
tzdata \
git \
curl \
gcc-aarch64-linux-gnu \
g++-aarch64-linux-gnu \
autoconf \
libtool \
pkg-config \
zip \
nano \
vim \
wget \
&& apt-get clean && rm -rf /var/lib/apt/lists/* \
&& wget -N https://kumisystems.dl.sourceforge.net/project/raspberry-pi-cross-compilers/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%209.2.0/Raspberry%20Pi%201%2C%20Zero/cross-gcc-9.2.0-pi_0-1.tar.gz && tar -xzf cross-gcc-9.2.0-pi_0-1.tar.gz -C /usr --strip-components=1 \
&& wget -N https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1-Linux-x86_64.tar.gz && tar -xzf cmake-3.18.1-Linux-x86_64.tar.gz -C /usr --strip-components=1 \
&& rm cross-gcc-9.2.0-pi_0-1.tar.gz cmake-3.18.1-Linux-x86_64.tar.gz && ln -fs /usr/share/zoneinfo/Europe/Vienna /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata \
&& curl -sL https://deb.nodesource.com/setup_14.x | bash - \
&& apt-get install -y nodejs
